### PR TITLE
Incoming interface

### PR DESCRIPTION
**Pull request by HRogge**
When building lowlevel network services with multiple interfaces, its often useful or even necessary to know the specific interface from which a Message was received from. This change uses the already existing packagecon in connUDP to get the interface from the operation system and stores it in the Message.

### CODE REVIEW

**Comment by HRogge** [comment]
I like the solution in https://github.com/plgd-dev/go-coap/tree/jkralik/feature/udp-propagate-interface

**Comment by HRogge** [comment]
@jkralik I tried to see if your feature branch provides what I need, but I got a compiler error net/dtlslistener.go:124

**Comment by HRogge** [comment]
want me to change this change to return the ControlMessage instead of interface index?

**Comment by Danielius1922** [comment]
> want me to change this change to return the ControlMessage instead of interface index?

Sorry @HRogge we are working on a release and some urgent bugs, hopefully everything will get sorted by the end of the week, we will check your work once we're finished with that. Thank you for your patience.

**Comment by jkralik** [comment]
> want me to change this change to return the ControlMessage instead of interface index?

@HRogge Absolutely, the control message is more general than the interface. Could you please enhance the content at https://github.com/plgd-dev/go-coap/tree/jkralik/feature/udp-propagate-interface and prepare it for merging? 🙏  ?

**Comment by HRogge** [comment]
Difficulties with pion-transport dependency go away when I merge the current master into https://github.com/plgd-dev/go-coap/tree/jkralik/feature/udp-propagate-interface

**Comment by HRogge** [comment]
@jkralik any timeline when/if you want to merge [jkralik/feature/udp-propagate-interface](https://github.com/plgd-dev/go-coap/tree/jkralik/feature/udp-propagate-interface)? I don't know at which part the branch is lacking, the feature that I tried to introduce with this PR is already present and working in your branch.

**Comment by jkralik** [comment]
Closing the PR because the feature has been implemented by #510

**Pull request closed without merging**
